model = "prod_sigmoid_pooling"

[[block]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 4

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 971
output_channel = 4
num_neighboring_features = 4

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "SigmoidProdPooling"
input_channel = 63
n_reads_per_site = 20
