[[block]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 4

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 971
output_channel = 4
num_neighboring_features = 4

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "Linear"
input_channel = 63
output_channel = 150
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 150
output_channel = 32
activation = "relu"
batch_norm = false

[[block]]
block_type = "ProbabilityAttention"
input_channel = 32
n_bins = 11
sigma = 0.1
hidden_layers_1 = [64, 32]
hidden_layers_2 = [64, 1]
activation = 'tanh'

[[block]]
block_type = "Linear"
input_channel = 352
output_channel = 64
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 64
output_channel = 32
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 32
output_channel = 2
activation = "softmax"
batch_norm = false
