[train_loss_function]
loss_function_type = "read_site_level_entropy_cluster"
mode = "prod_pooling"
lambda_1 = 1
lambda_2 = 1
lambda_3 = 1

[test_loss_function]
loss_function_type = "binary_cross_entropy_loss"

[dataset]
root_dir = "/home/christopher/hct116_dataprep_5_neighbors"
min_reads = 20
norm_path = "/home/christopher/hct116_dataprep_5_neighbors/norm_dict.joblib"   
num_neighboring_features=1

[dataloader]
    [dataloader.train]
    batch_size = 256
    sampler = "ImbalanceOverSampler"

    [dataloader.test]
    batch_size = 256
    shuffle = false

    [dataloader.val]
    batch_size = 256
    shuffle = false