FROM python:3.8-slim
USER root

LABEL maintainer="Christopher Hendra <chrishendra93@gmail.com>"

##Set environment variables
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

COPY . /m6anet
WORKDIR /m6anet
RUN python /m6anet/setup.py develop

ENTRYPOINT  ["m6anet-dataprep"]


# RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
#     wget --quiet https://repo.continuum.io/archive/Anaconda3-5.0.0.1-Linux-x86_64.sh -O ~/anaconda.sh && \
#     /bin/bash ~/anaconda.sh -b -p /opt/conda && \
#     rm ~/anaconda.sh



# ENV PATH /opt/conda/bin:$PATH


# RUN pip --no-cache-dir install --upgrade \
#         altair \
#         sklearn-pandas

# # Open Ports for Jupyter
# EXPOSE 7745

# #Setup File System
# RUN mkdir ds
# ENV HOME=/ds
# ENV SHELL=/bin/bash
# VOLUME /ds
# WORKDIR /ds
# ADD run_jupyter.sh /ds/run_jupyter.sh
# RUN chmod +x /ds/run_jupyter.sh

# # Run a shell script
# CMD  ["./run_jupyter.sh"]