[train_loss_function]
loss_function_type = "binary_cross_entropy_loss"

[test_loss_function]
loss_function_type = "binary_cross_entropy_loss"

[dataset]
root_dir = "/home/christopher/hct116_dataprep_5_neighbors"
min_reads = 20
norm_path = "/home/christopher/hct116_dataprep_5_neighbors/norm_dict_nanopolish.joblib"   
num_neighboring_features = 0
site_mode = true

[dataloader]
    [dataloader.train]
    batch_size = 256
    sampler = "ImbalanceOverSampler"

    [dataloader.test]
    batch_size = 256
    shuffle = false

    [dataloader.val]
    batch_size = 256
    shuffle = false