config_name = "nanopolish_undersampled"

[train_loss_function]
loss_function_type = "binary_cross_entropy_loss"

[test_loss_function]
loss_function_type = "binary_cross_entropy_loss"

[dataset]
data_path = "/home/christopher/hct116_mad_normed_site_info/site_info.csv.tar.gz"
    
    [dataset.transform_function]
    transform_name = "identity_transform"

    [dataset.train]
    dataset_class = "NanopolishTrainDS"
    norm_path = "/home/christopher/hct116_mad_normed_site_info/norm_dict_nanopolish.joblib"
    n_reads_per_site = 20
    num_neighboring_features = 0

    [dataset.test]
    dataset_class = "NanopolishTestDS"
    norm_path = "/home/christopher/hct116_mad_normed_site_info/norm_dict_nanopolish.joblib"
    n_reads_per_site = 20
    num_neighboring_features = 0

    [dataset.val]
    dataset_class = "NanopolishTestDS"
    norm_path = "/home/christopher/hct116_mad_normed_site_info/norm_dict_nanopolish.joblib"
    n_reads_per_site = 20
    num_neighboring_features = 0
    
[dataloader]
    [dataloader.collate_fn]
    collate_fn = "kmer_collate"

    [dataloader.train]
    batch_size = 256
    sampler = "ImbalanceSampler"

    [dataloader.test]
    batch_size = 256
    shuffle = false

    [dataloader.val]
    batch_size = 256
    shuffle = false