[loss_function]
loss_function_type = "binary_cross_entropy_loss"

[dataset]
root_dir = "/home/christopher/hct116_dataprep_5_neighbors/"
min_reads = 20
norm_path = "/home/christopher/m6anet/m6anet/model/norm_factors/norm_dict.joblib"
num_neighboring_features = 1

[dataloader]
    [dataloader.train]
    batch_size = 256
    sampler = "ImbalanceOverSampler"

    [dataloader.val]
    batch_size = 256
    shuffle = false

    [dataloader.test]
    batch_size = 256
    shuffle = false
