model = "mean_sigmoid_pooling"

[[block]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 0

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 18
output_channel = 2
num_neighboring_features = 0

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "Linear"
input_channel = 5
output_channel = 150
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 150
output_channel = 32
activation = "relu"
batch_norm = true

[[block]]
block_type = "SigmoidMeanPooling"
input_channel = 32
n_reads_per_site = 20
