model = "prod_sigmoid_pooling"

[[block]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 0

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 18
output_channel = 2
num_neighboring_features = 0

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "SigmoidProdPooling"
input_channel = 5
n_reads_per_site = 20
