[[block]]
block_type = "DeaggregateNanopolish"
num_neighboring_features = 2

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 288
output_channel = 3
num_neighboring_features = 2

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "Linear"
input_channel = 30
output_channel = 150
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 150
output_channel = 32
activation = "relu"
batch_norm = false

[[block]]
block_type = "SummaryStatsProbability"
input_channel = 32
n_reads_per_site = 20

[[block]]
block_type = "Linear"
input_channel = 160
output_channel = 64
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 64
output_channel = 32
activation = "relu"
batch_norm = true

[[block]]
block_type = "Linear"
input_channel = 32
output_channel = 2
activation = "softmax"
batch_norm = false
