model = "m6ANet_simple_summary_stats"

[[block]]
block_type = "SummaryStatsAggregator"
input_channel = 15
n_reads_per_site = 20

[[block]]
block_type = "KmerMultipleEmbedding"
input_channel = 288
output_channel = 2
num_neighboring_features = 2

[[block]]
block_type = "ConcatenateFeatures"

[[block]]
block_type = "Linear"
input_channel = 85
output_channel = 1
activation = "sigmoid"
batch_norm = false
