name: Publish to PyPI.org
on:
  release:
    types: [published]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: build
        run: python -m pip install --upgrade build && python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}